# Generated by Django 2.1.15 on 2022-03-20 21:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20220316_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('no_one', models.CharField(blank=True, max_length=280)),
                ('no_two', models.CharField(blank=True, max_length=280)),
            ],
        ),
    ]
